### PR TITLE
Remove ack and CoffeeTags

### PR DESCRIPTION
**Pull request by mattjmorrison**
I don't *think* these are probably used anymore....

### CODE REVIEW

**Comment by JarrodCTaylor** [comment]
Yeah. The coffee stuff has been a dead man walking for awhile. Do you want to all of the other coffee related stuff in this PR?

**Comment by mattjmorrison** [comment]
Yeah, I'll get that stuff added this evening. What about `ack` - is that used anymore after `ag`?

**Comment by JarrodCTaylor** [comment]
Ack gets no love anymore as far as I know. It's just a freeloader and it needs to go

**Comment by mattjmorrison** [comment]
I think I got all of the coffee stuff out of there.

**Pull request merged**
