### PR TITLE
Use eslint for javascript linting

### PR DESCRIPTION
**Pull request by dustinfarris**

### CODE REVIEW

**Comment by JarrodCTaylor** [comment]
What's the rationale behind this one,  given that the latest version of ember is still shipping with jshint?

**Comment by dustinfarris** [comment]
jshint is EOL.  i'm using eslint for es7 support.. but understand if not ready for this yet.

**Comment by JarrodCTaylor** [comment]
Interesting.  I have missed the conversations about it being in the life.  Is that ember specific or in general?  Are you pulling it out of your current ember projects and replacing it with eslint?

**Comment by dustinfarris** [comment]
I got my wires crossed, sorry.  [JSCS](http://jscs.info/) is EOL, not jshint.

At any rate, eslint has support for experimental/es7 features (such as object spread)—so, yes, I am moving to eslint.

**Comment by JarrodCTaylor** [comment]
Ahh got you. Let's stick with what ember is shipping with and update when that changes.

**Pull request closed without merging**
